Front-end/UserInterface/Controllers/BasketController.cs
using CarRental.Shared.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UserInterface.MicroserviceCommunication.Abstract;
using UserInterface.Models.Baskets;
using UserInterface.Models.CatalogModels;
using UserInterface.Models.Discount;

namespace UserInterface.Controllers
{
    [Authorize]
    public class BasketController : Controller
    {
        private readonly ICatalogService _catalogService;
        private readonly IBasketService _basketService;
        private readonly ISharedIdentityService _sharedIdentityService;

        public BasketController(ICatalogService catalogService, IBasketService basketService, ISharedIdentityService sharedIdentityService)
        {
            _catalogService = catalogService;
            _basketService = basketService;
            _sharedIdentityService = sharedIdentityService; 
        }

        public async Task<IActionResult> Index()
        {
            return View(await _basketService.GetBasket());
        }

        public async Task<IActionResult> ApplyDiscount(DiscountViewModel discountViewModel)
        {
            if (!ModelState.IsValid)
            {
                TempData["discountError"] = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).First();
            }
            var status = await _basketService.ApplyDiscount(discountViewModel.Code);
            TempData["status"] = status;
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> CancelAppliedDiscount()
        {
            await _basketService.CancelTheDiscount();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> AddBasketItems(string carId, DateTime rentDate,DateTime leaveDate)
        {
            var car = await _catalogService.GetByCarId(carId);
            TimeSpan duration = leaveDate - rentDate;
            var days = duration.Days;
            var basketItem = new BasketItemViewModel
            {
                UserId=_sharedIdentityService.GetUserId,
                CarId = car.Id,
                CarName = car.Name,
                Price = car.Price*days,
                RentDate=rentDate,
                LeaveDate=leaveDate,    

            };

            await _basketService.AddBasketItem(basketItem);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> DeleteBasketItems(string carId)
        {
            await _basketService.RemoveBasketItem(carId);
            return RedirectToAction(nameof(Index));
        }
    }
}

Front-end/UserInterface/Controllers/CarsController.cs
using CarRental.Shared.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Build.Evaluation;
using UserInterface.MicroserviceCommunication.Abstract;
using UserInterface.Models.CatalogModels;

namespace UserInterface.Controllers
{
    [Authorize]
    public class CarsController : Controller
    {
        private readonly ICatalogService _catalogService;
        private readonly ISharedIdentityService _sharedIdentityService;

        public CarsController(ICatalogService catalogService, ISharedIdentityService sharedIdentityService)
        {
            _catalogService = catalogService;
            _sharedIdentityService = sharedIdentityService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _catalogService.GetAllCarsByUserId(_sharedIdentityService.GetUserId));
        }
        public async Task<IActionResult> Create()
        {
            var categories = await _catalogService.GetAllCategoryAsync();
            ViewBag.categoryList = new SelectList(categories, "Id", "Name");
            return View();
        }
        public async Task<IActionResult> CurrentlyRentedCars()
        {
            var userId = _sharedIdentityService.GetUserId;
            var response = await _catalogService.GetCurrentlyRentedCars(userId);
            return View(response);
        }

        public async Task<IActionResult> GetCarsBasedOnPassive()
        {
            var userId = _sharedIdentityService.GetUserId;
            var response = await _catalogService.GetAllPassiveCarsBasedOnUserId(userId);
            return View(response);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CarCreate carCreate)
        {
            var categories = await _catalogService.GetAllCategoryAsync();

            ViewBag.categoryList = new SelectList(categories, "Id", "Name");
            carCreate.UserId = _sharedIdentityService.GetUserId;
            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors);
            }

            await _catalogService.AddCarAsync(carCreate);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(string id)
        {
            var cars = await _catalogService.GetByCarId(id);
            var categories = await _catalogService.GetAllCategoryAsync();

            if (cars == null)
            {
                RedirectToAction(nameof(Index));
            }
            ViewBag.categoryList = new SelectList(categories, "Id", "Name");
            CarUpdate carUpdate = new CarUpdate
            {
                Id = cars.Id,
                Name = cars.Name,
                UserId = cars.UserId,
                Price = cars.Price,
                Description = cars.Description,
                Feature = cars.Feature != null && cars.Feature.Duration != null ? new FeatureViewModel { Duration = cars.Feature.Duration } : null,


                CategoryId = cars.CategoryId,
                Picture = cars.Picture,
                Location = cars.Location

            };

            return View(carUpdate);

        }
        [HttpPost]
        public async Task<IActionResult> Update(CarUpdate carUpdate)
        {
            var categories = await _catalogService.GetAllCategoryAsync();
            ViewBag.categoryList = new SelectList(categories, "Id", "Name", carUpdate.Id);
            if (!ModelState.IsValid)
            {
                return View();
            }
            await _catalogService.UpdateCarAsync(carUpdate);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(string id)
        {
            await _catalogService.DeleteCarAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Front-end/UserInterface/Controllers/OrderController.cs
using CarRental.Shared.Services;
using Microsoft.AspNetCore.Mvc;
using UserInterface.MicroserviceCommunication.Abstract;
using UserInterface.Models.Orders;

namespace UserInterface.Controllers
{
    public class OrderController : Controller
    {
        private readonly IBasketService _basketService;
        private readonly IOrderService _orderService;
        private readonly ISharedIdentityService _sharedIdentityService;
        

        public OrderController(IBasketService basketService, IOrderService orderService,ISharedIdentityService identity)
        {
            _basketService = basketService;
            _orderService = orderService;
            _sharedIdentityService = identity;  
        }

        public async Task<IActionResult >PayPage()
        {
            var basket = await _basketService.GetBasket();
            ViewBag.basket = basket;
            
            return View(new CheckOutModel());
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(CheckOutModel checkOut)
        {
            var orderStatus = await _orderService.QueueOrder(checkOut);
            if (!orderStatus.IsSuccessful)
            {
                var basket = await _basketService.GetBasket();
                ViewBag.basket = basket;
                ViewBag.error = orderStatus.Error;
                return View();

            }
            return RedirectToAction(nameof(SuccessfulOut), new { orderId = new Random().Next(1,10000) });

        }

        public IActionResult SuccessfulOut(int orderId)
        {
            ViewBag.orderId = orderId;
            return View();
        }
        public async Task<IActionResult >OrderHistory()
        {

            return View(await _orderService.GetOrder());
        }
    }
}

Front-end/UserInterface/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using UserInterface.MicroserviceCommunication.Abstract;
using UserInterface.Models;

namespace UserInterface.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public async Task<IActionResult >Index()
        {
            return View(await _userService.GetUser());
        }

    }
}

Front-end/UserInterface/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UserInterface</title>
    <link href="~/lib/bootstrap-5.3.0-dist/css/bootstrap.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UserInterface.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rent A Car</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                        </li>
                        <li class="nav-item">

                            @if (!User.Identity.IsAuthenticated)
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="FrontSignUp">Kayıt ol</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="SigningIn">Giriş yap</a>
                            </li>
                            }

                    </ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    @User.Identity.Name
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-controller="User" asp-action="Index">Profil</a></li>
                                    <li><a class="dropdown-item" asp-controller="Cars" asp-action="Index">Arabalarım</a></li>
                                    <li><a class="dropdown-item" asp-controller="Cars" asp-action="GetCarsBasedOnPassive">İlanda olmayan arabalarım</a></li>
                                    <li><a class="dropdown-item" asp-controller="Cars" asp-action="CurrentlyRentedCars">Kiradaki Araçlarım</a></li>
                                    <li><a class="dropdown-item" asp-controller="Basket" asp-action="Index">Sepet</a></li>
                                    <li><a class="dropdown-item" asp-controller="Order" asp-action="OrderHistory">Kiralama Geçmişi</a></li>
                                    <li><a class="dropdown-item" asp-controller="Authentication" asp-action="Logout">Çıkış</a></li>
                                    
                                    <li><hr class="dropdown-divider"></li>

                                </ul>
                            </li>
                        </ul>
                    }
                    else
                    {






                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/bootstrap-5.3.0-dist/js/bootstrap.bundle.min.js"></script>


    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>